### ISSUE TITLE
Php extension name

### ISSUE THREAD

**Issue by diegomsana** [toymachine/libredis#1]
Hi,

There's already a php extension named "redis", so when i install this php extension it causes a conflict. Maybe you should rename yours to libredis.

**Comment by toymachine** [comment]
fixed, it is now libredis (.so)

**Comment by diegomsana** [comment]
Nice. I finally gave it a try yesterday and loved the performance. I'll probably build a high-level pure php library on top of it. Keep up the good work :)

**Comment by toymachine** [comment]
why not adapt something like predis on top of it?
