### ISSUE TITLE
batch->write results in an empty reply stack

### ISSUE THREAD

**Issue by philjohn** [toymachine/libredis#2]
When using batch->cmd(), the batch->next_reply semantics work as expected, however, when using the more generic ->write(), calling batch->next_reply returns false straight away, even if a multibatch or other response would normally be returned by Redis 2.0.0

The following code shows this:

<pre>
&lt;?php
$redis = Libredis();
$conn = $redis->get_connection('127.0.0.1:6379');
$batch = $redis->create_batch();
$batch->write("KEYS *\r\n");
$conn->execute($batch);
while($batch->next_reply($type, $value, $length))
{
    echo "TYPE  : {$type}\n";
    echo "VALUE : {$value}\n";
    echo "LENGTH: {$length}\n";
}
</pre>

If you execute that from the commandline, nothing is output.  Changing ->write("KEYS _\r\n") to cmd("KEYS", "_") yields the expected result (a multibatch response).

**Comment by philjohn** [comment]
Sorry, just realised I need to pass the number of commands I'm writing (I think) as the 2nd parameter of batch->write, doing that makes it work as expected.

**Comment by toymachine** [comment]
you are correct. this you would usually pass in the last call to write.
