### ISSUE TITLE
Would be good to pass an array of arguments to the batch->cmd method

### ISSUE THREAD

**Issue by philjohn** [toymachine/libredis#3]
At the moment, batch->cmd allows a string as the argument, and allows multiple arguments to be passed.

Sometimes I'll have multiple arguments, but they are in an array, it would be good if an array could be passed to the batch->cmd method and treated as if it has been called with multiple parameters, e.g.

What we can currently do
<code>
$batch->cmd('SINTER', 'set:1', 'set:2', 'set:3');
</code>

What it would be nice to do
<code>
$params = array('set:1', 'set:2', 'set:3'); //setting here as an example only, actual params could have come from anywhere
$batch->cmd('SINTER', $params);
</code>

**Comment by toymachine** [comment]
you can use the php function call_user_func_array for this:

call_user_func_array(array($batch, 'cmd'), $params);
